name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - mlproj-vehicle  # Change this to your default branch if it's different
  workflow_dispatch:
    branches:
      - mlproj-vehicle

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS region
        run: aws configure set region us-east-1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: AKIAV565HMWWL5ESBBQ4.dkr.ecr.us-east-1.amazonaws.com/mithml
          mask-password: true
          registry-type: private
          skip-logout: false

      - name: Build Docker image
        run: |
          cd turicreateml/  # Navigate to the folder containing the Dockerfile
          docker build -t my-app .

      - name: Tag Docker image
        run: |
          docker tag my-app:latest AKIAV565HMWWL5ESBBQ4.dkr.ecr.us-east-1.amazonaws.com/my-app:model_sensor_raw

      - name: Push Docker image to Amazon ECR
        run: |
          docker push AKIAV565HMWWL5ESBBQ4.dkr.ecr.us-east-1.amazonaws.com/my-app:model_sensor_raw
